"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['wbXmlParser.py']
DATA_FILES = ['main_window.py']
OPTIONS = {'iconfile': '/Users/lego/workspace/wbXmlParser/Application.png'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
